language: java
jdk: oraclejdk8

sudo: required

before_install:
  - chmod +x mvnw

# Code coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)

# cache between builds
cache:
  directories:
  - $HOME/.m2